### ISSUE TITLE
shard name (CrystalIrc) doesn't match dependency name (Crirc)

### ISSUE THREAD

**Issue by g33kidd** [Meoowww/Crirc#11]
What's going on with this? I don't understand. I'm trying to install Crirc, but it's installing the old one when I try using this in my shard.yml file. But if I change it to Crirc, it doesn't do anything?

```
dependencies:
  CrystalIrc:
    github: Meoowww/Crirc
```

**Comment by Nephos** [comment]
I'll take a look quickly

**Comment by Nephos** [comment]
Ok here the solution:

I must fix the readme (I forgot to replace some CrystalIrc items with Crirc). There is maybe an issue with the Case, i'll take a look

```yaml
dependencies:
  crirc:
    github: Meoowww/Crirc
    branch: master
```

Please let me know if it works for you :)
